/*
 * keyboard.c
 *
 *  Created on: 27 de jan de 2017
 *      Author: Abdoral Timóteo
 *
 * Realiza a leitura do teclado
 *
 */

#include "gpio.h"

char* readKeyBoard(){
	char *botao;

	HAL_Delay(1);
	if(HAL_GPIO_ReadPin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin) == GPIO_PIN_SET){
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_RESET);

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL0_GPIO_Port, KEYPAD_PIN_COL0_Pin)== GPIO_PIN_SET)
			return botao="1";

		if(HAL_GPIO_ReadPin(COLUNA1_GPIO_Port, COLUNA1_Pin)== GPIO_PIN_SET)
			return botao="2";

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL2_GPIO_Port, KEYPAD_PIN_COL2_Pin)== GPIO_PIN_SET)
			return botao="3";


		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL3_GPIO_Port, KEYPAD_PIN_COL3_Pin)== GPIO_PIN_SET)
			return botao="A";

		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_SET);
	}

	HAL_Delay(1);
	if(HAL_GPIO_ReadPin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin) == GPIO_PIN_SET){
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_RESET);

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL0_GPIO_Port, KEYPAD_PIN_COL0_Pin)== GPIO_PIN_SET)
			return botao="4";

		if(HAL_GPIO_ReadPin(COLUNA1_GPIO_Port, COLUNA1_Pin)== GPIO_PIN_SET)
			return botao="5";

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL2_GPIO_Port, KEYPAD_PIN_COL2_Pin)== GPIO_PIN_SET)
			return botao="6";


		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL3_GPIO_Port, KEYPAD_PIN_COL3_Pin)== GPIO_PIN_SET)
			return botao="B";

		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_SET);
	}

	HAL_Delay(1);
	if(HAL_GPIO_ReadPin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin) == GPIO_PIN_SET){
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_RESET);

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL0_GPIO_Port, KEYPAD_PIN_COL0_Pin)== GPIO_PIN_SET)
			return botao="7";

		if(HAL_GPIO_ReadPin(COLUNA1_GPIO_Port, COLUNA1_Pin)== GPIO_PIN_SET)
			return botao="8";

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL2_GPIO_Port, KEYPAD_PIN_COL2_Pin)== GPIO_PIN_SET)
			return botao="9";


		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL3_GPIO_Port, KEYPAD_PIN_COL3_Pin)== GPIO_PIN_SET)
			return botao="C";

		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin,GPIO_PIN_SET);
	}

	HAL_Delay(1);
	if(HAL_GPIO_ReadPin(KEYPAD_PIN_ROW3_GPIO_Port, KEYPAD_PIN_ROW3_Pin) == GPIO_PIN_SET){
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_RESET);

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL0_GPIO_Port, KEYPAD_PIN_COL0_Pin)== GPIO_PIN_SET)
			return botao="*";

		if(HAL_GPIO_ReadPin(COLUNA1_GPIO_Port, COLUNA1_Pin)== GPIO_PIN_SET)
			return botao="0";

		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL2_GPIO_Port, KEYPAD_PIN_COL2_Pin)== GPIO_PIN_SET)
			return botao="#";


		if(HAL_GPIO_ReadPin(KEYPAD_PIN_COL3_GPIO_Port, KEYPAD_PIN_COL3_Pin)== GPIO_PIN_SET)
			return botao="D";

		HAL_GPIO_WritePin(KEYPAD_PIN_ROW0_GPIO_Port, KEYPAD_PIN_ROW0_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW1_GPIO_Port, KEYPAD_PIN_ROW1_Pin,GPIO_PIN_SET);
		HAL_GPIO_WritePin(KEYPAD_PIN_ROW2_GPIO_Port, KEYPAD_PIN_ROW2_Pin,GPIO_PIN_SET);
	}




    return botao="E";
}



